services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: openbcg
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:80"
    environment:
      DATABASE_URL: postgresql://postgres:password@db:5432/openbcg
    depends_on:
      - db

volumes:
  postgres_data:
